apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-row
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  cachingMode: None
  skuName: PremiumV2_LRS
  DiskIOPSReadWrite: "5000"
  DiskMBpsReadWrite: "1200"
allowVolumeExpansion: true
