name: TF/Shell Linters
on:
  pull_request:
    types:
      - opened
      - edited
jobs:
  lint-terraform:
    name: Lint TF
    runs-on: ubuntu-latest
    steps:
      - name: Lint Terraform
        uses: hashicorp/terraform:1.5.7
        run: |
          terraform fmt -recursive
      
  lint-shell:
    name: Lint Shell
    runs-on: ubuntu-latest
    steps:
      - name: Lint title
        uses: koalaman/shellcheck:0.11.0
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck --severity=style
