name: Run Terraform fmt diff

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    name: Check Terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run terraform fmt diff
        run: terraform fmt -diff -recursive -write=false

      - name: run terraform fmt diff
        run: terraform fmt -diff -recursive -write=false > diff.txt

      - name: check for empty diff
        id: diff_check
        run: |
          if [[ -s diff.txt ]]; then
            echo "::error file=diff.txt::formatting changes found"
            echo $(cat diff.txt)
            exit 1
          else
            echo "TERRAFORM_DIFF=false" >> $GITHUB_ENV
          fi

